name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pypa/hatch@install
      - run: hatch run types:check
  fmt:
    name: Format and lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pypa/hatch@install
      - run: hatch fmt --check

  tests:
    name: Tests
    runs-on: ubuntu-22.04
    env:
      CLEANLAB_TLM_API_KEY: ${{ secrets.CLEANLAB_TLM_API_KEY }}
    strategy:
      matrix:
        # Only run the full matrix when called from the release workflow (release.yml)
        # This ensures comprehensive testing before publishing to PyPI
        python: ${{ github.event_name != 'workflow_call' && fromJSON('["3.12"]') || fromJSON('["3.9", "3.10", "3.11", "3.12", "3.13"]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code-changes:
              - '!**.md'
              - '!LICENSE'
              - '!**.gitignore'
              - '!src/cleanlab_tlm/__about__.py'
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: pypa/hatch@install
      - name: Run tests with coverage
        if: steps.filter.outputs.code-changes == 'true'
        run: hatch test -v --cover --include python=${{ matrix.python }}
