name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: pypa/hatch@install
      - run: hatch run types:check
  fmt:
    name: Format and lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: pypa/hatch@install
      - run: hatch fmt --check
  test:
    name: Test
    runs-on: ubuntu-22.04
    env:
      CLEANLAB_TLM_API_KEY: ${{ secrets.CLEANLAB_TLM_API_KEY }}
    strategy:
      matrix:
        include:
          - python: "3.8"
            if: github.event_name != 'pull_request'
          - python: "3.9"
            if: github.event_name != 'pull_request'
          - python: "3.10"
            if: github.event_name != 'pull_request'
          - python: "3.11"
            if: github.event_name != 'pull_request'
          - python: "3.12" # On PRs, only run tests with one version
          - python: "3.13"
            if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - uses: pypa/hatch@install
      - run: hatch test -v --cover --include python=$(echo ${{ matrix.python }})
